name       : libheif
version    : 1.4.0
release    : 5
source     :
    - https://github.com/strukturag/libheif/archive/v1.4.0.tar.gz : 3b7cead51077ee42e687248b8cd9269fda95a5f7ef4e502c54d08d189e395368
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) image coding for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. Alternative codecs for, e.g., AVC and JPEG can be provided as plugins.
builddeps  :
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(x265)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
