name       : libheif
version    : 1.16.1
release    : 32
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.16.1/libheif-1.16.1.tar.gz : ac15b54b6d7c315710e156d119b8a1bfc89f29621e99222b2750b1f31c9c3558
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format) file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) or AV1 image coding, respectively, for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. For AVIF, libaom, dav1d, rav1e, or SVT-AV1 are used as codecs.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(rav1e)
    - pkgconfig(x265)
setup      : |
    %cmake_ninja -DWITH_RAV1E_PLUGIN=OFF -DWITH_SvtEnc_PLUGIN=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Remove empty dir
    rmdir $installdir/usr/lib64/libheif
