name       : libheif
version    : 1.8.0
release    : 14
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.8.0/libheif-1.8.0.tar.gz : e43ef91a5ad41de4471a2fd484279d0793b419009a7d102965739da8f7b75d96
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) image coding for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. Alternative codecs for, e.g., AVC and JPEG can be provided as plugins.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(rav1e)
    - pkgconfig(x265)
setup      : |
    %patch -p1 < $pkgfiles/0000-enable-compilation-with-system-rav1e.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
