name       : libheif
version    : 1.3.2
release    : 3
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.3.2/libheif-1.3.2.tar.gz : a9e12a693fc172baa16669f427063edd7bf07964a1cb623ee57cd056c06ee3fc
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) image coding for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. Alternative codecs for, e.g., AVC and JPEG can be provided as plugins.
builddeps  :
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(x265)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
