name       : libheif
version    : 1.5.0
release    : 6
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.5.0/libheif-1.5.0.tar.gz : 0d03f59cb5a71fbe08f4ac72d2dc4d7888b91fa4ef8e1c80189df3ca08facdb9
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) image coding for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. Alternative codecs for, e.g., AVC and JPEG can be provided as plugins.
builddeps  :
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(x265)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
