name       : libheif
version    : 1.12.0
release    : 24
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.12.0/libheif-1.12.0.tar.gz : e1ac2abb354fdc8ccdca71363ebad7503ad731c84022cf460837f0839e171718
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format) file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) or AV1 image coding, respectively, for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. For AVIF, libaom, dav1d, or rav1e are used as codecs.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(rav1e)
    - pkgconfig(x265)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
