name       : libheif
version    : 1.9.1
release    : 16
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.9.1/libheif-1.9.1.tar.gz : 5f65ca2bd2510eed4e13bdca123131c64067e9dd809213d7aef4dc5e37948bca
license    : LGPL-3.0-or-later
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format) file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) or AV1 image coding, respectively, for the best compression ratios currently possible.

    libheif makes use of libde265 for the actual image decoding and x265 for encoding. For AVIF, libaom, dav1d, or rav1e are used as codecs.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(rav1e)
    - pkgconfig(x265)
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-compilation-with-system-dav1d-and-rav1e.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
